name: Coverage

# Controls when the action will run.
on:
  pull_request:
    branches:
      - "**" # Pull request targeting any branch
  push:
    branches:
      - "master" # Push to master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Install Rust
        run: ./scripts/init.sh

      - name: Install Rustup component
        run: rustup component add llvm-tools-preview

      - name: Install grcov
        run: cargo install grcov

      - name: Run Tests
        run: cargo test -p eigen-trust-protocol --verbose -- --nocapture
        env:
          RUSTFLAGS: "-Zinstrument-coverage"
          LLVM_PROFILE_FILE: "coverage-%p-%m.profraw"

      - name: Generate Coverage data
        run: grcov . -s . --binary-path ./target/debug/ --ignore-not-existing --ignore **/lib.rs -t lcov -o cov.info

      - uses: codecov/codecov-action@v3
        with:
          files: ./cov.info
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: true