name: Build & Test Circuits, Server, Client

# Controls when the action will run.
on:
  pull_request:
    branches:
      - "**" # Pull request targeting any branch
  push:
    branches:
      - "master" # Push to master branch

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.3.0

      - name: Set-Up
        run: ./scripts/init.sh

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1

      - name: Fmt Check
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1
        with: 
          args: --exit-code
            
      - name: Clippy Check
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - uses: taiki-e/install-action@nextest

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --all